***************
*** 1,7 ****
  # SPDX-License-Identifier: GPL-2.0
  VERSION = 4
  PATCHLEVEL = 17
- SUBLEVEL = 5
  EXTRAVERSION =
  NAME = Merciless Moray
  
--- 1,7 ----
  # SPDX-License-Identifier: GPL-2.0
  VERSION = 4
  PATCHLEVEL = 17
+ SUBLEVEL = 6
  EXTRAVERSION =
  NAME = Merciless Moray
  
